### ISSUE TITLE
Incorrect Copyright, missing identifier

### ISSUE THREAD

**Issue by keeyzar** [vsevel/quarkus-admission-controller#3]
Hey,
I'm currently integrating your license into my derivative work, unfortunately it's impossible to link the work back to you, when the identifier is missing

At line 189 in the LICENSE file you need to fill out these brackets []
   Copyright [yyyy] [name of copyright owner]

Thanks again for providing the code and adding a license!

**Comment by vsevel** [comment]
hello. I have added the missing information.
